# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CervellaSwarm Contributors

"""Integration tests for lean4_bridge.py.

Verifies the generated Lean 4 code structure, correctness of output
for all standard protocols, and edge cases.
All tests run without Lean 4 installed.
"""

import re
import unittest.mock as mock

import pytest

from cervellaswarm_lingua_universale.lean4_bridge import (
    ALL_PROPERTIES,
    FLAT_PROPERTIES,
    Lean4Generator,
    Lean4Verifier,
    VerificationProperty,
    VerificationReport,
    VerificationResult,
    _has_choices,
    generate_lean4,
    generate_lean4_multi,
    lean4_available,
)
from cervellaswarm_lingua_universale.protocols import (
    ArchitectFlow,
    DelegateTask,
    Protocol,
    ProtocolChoice,
    ProtocolStep,
    ResearchFlow,
    SimpleTask,
)
from cervellaswarm_lingua_universale.types import MessageKind


# ============================================================
# Helpers
# ============================================================


def make_custom_protocol(name="Custom", roles=("x", "y"), kind=MessageKind.DM) -> Protocol:
    """Build a simple custom (non-standard) flat protocol."""
    return Protocol(
        name=name,
        roles=roles,
        elements=(
            ProtocolStep(sender=roles[0], receiver=roles[1], message_kind=kind),
        ),
    )


STANDARD_PROTOCOLS = {
    "DelegateTask": DelegateTask,
    "ArchitectFlow": ArchitectFlow,
    "ResearchFlow": ResearchFlow,
    "SimpleTask": SimpleTask,
}

FLAT_PROTOCOLS = {
    "DelegateTask": DelegateTask,
    "ResearchFlow": ResearchFlow,
    "SimpleTask": SimpleTask,
}

CHOICE_PROTOCOLS = {
    "ArchitectFlow": ArchitectFlow,
}


# ============================================================
# 1. Generated code contains correct Lean 4 keywords
# ============================================================


class TestLean4Keywords:
    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_inductive_keyword(self, name, protocol):
        code = generate_lean4(protocol)
        assert "inductive" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_structure_keyword(self, name, protocol):
        code = generate_lean4(protocol)
        assert "structure" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_theorem_keyword(self, name, protocol):
        code = generate_lean4(protocol)
        assert "theorem" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_by_decide_tactic(self, name, protocol):
        code = generate_lean4(protocol)
        assert "by decide" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_deriving_clause(self, name, protocol):
        code = generate_lean4(protocol)
        assert "deriving" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_def_keyword(self, name, protocol):
        code = generate_lean4(protocol)
        assert "def " in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_contains_list_type(self, name, protocol):
        code = generate_lean4(protocol)
        assert "List " in code


# ============================================================
# 2. Correct structure: header, types, protocol, theorems
# ============================================================


class TestGeneratedStructure:
    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_has_auto_generated_header(self, name, protocol):
        code = generate_lean4(protocol)
        assert "Auto-generated by CervellaSwarm Lean 4 Bridge" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_has_protocol_name_in_header(self, name, protocol):
        code = generate_lean4(protocol)
        assert f"Protocol: {name}" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_has_do_not_edit_comment(self, name, protocol):
        code = generate_lean4(protocol)
        assert "DO NOT EDIT" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_types_section_comes_before_protocol_section(self, name, protocol):
        code = generate_lean4(protocol)
        # "-- Types" only appears once (as section header), after the file header
        types_pos = code.index("-- Types\n")
        # The protocol section is marked by a separator + protocol name line.
        # We find the section separator that immediately precedes "-- Protocol: {name}"
        # and comes AFTER the Types section.
        # The separator line is "-- ============..." followed by "-- Protocol: {name}"
        section_marker = f"-- ============================================================\n-- Protocol: {name}\n-- ======"
        protocol_section_pos = code.index(section_marker)
        assert types_pos < protocol_section_pos

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_protocol_section_comes_before_theorems_section(self, name, protocol):
        code = generate_lean4(protocol)
        protocol_pos = code.index(f"-- Protocol: {name}")
        theorems_pos = code.index("-- Theorems")
        assert protocol_pos < theorems_pos

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_message_kind_before_protocol_step(self, name, protocol):
        code = generate_lean4(protocol)
        mk_pos = code.index("inductive MessageKind")
        ps_pos = code.index("structure ProtocolStep")
        assert mk_pos < ps_pos


# ============================================================
# 3. Theorem count per protocol
# ============================================================


class TestTheoremCount:
    @pytest.mark.parametrize("name,protocol", FLAT_PROTOCOLS.items())
    def test_flat_protocol_has_five_theorems(self, name, protocol):
        gen = Lean4Generator()
        code = gen.generate_theorems(protocol)
        count = len(re.findall(r"^theorem ", code, re.MULTILINE))
        assert count == 5, f"{name}: expected 5 theorems, got {count}"

    def test_architect_flow_has_seven_theorems(self):
        gen = Lean4Generator()
        code = gen.generate_theorems(ArchitectFlow)
        count = len(re.findall(r"^theorem ", code, re.MULTILINE))
        assert count == 7, f"ArchitectFlow: expected 7 theorems, got {count}"

    def test_custom_choice_protocol_has_seven_theorems(self):
        """Protocol with one choice gets 5 + 2 = 7 theorems."""
        proto = Protocol(
            name="WithChoice",
            roles=("a", "b", "c"),
            elements=(
                ProtocolChoice(
                    decider="a",
                    branches={
                        "go": (
                            ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.DM),
                        ),
                        "stop": (
                            ProtocolStep(sender="a", receiver="c", message_kind=MessageKind.BROADCAST),
                        ),
                    },
                ),
            ),
        )
        gen = Lean4Generator()
        code = gen.generate_theorems(proto)
        count = len(re.findall(r"^theorem ", code, re.MULTILINE))
        assert count == 7


# ============================================================
# 4. Lean 4 syntax patterns (regex checks)
# ============================================================


class TestLean4SyntaxPatterns:
    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_inductive_has_constructors(self, name, protocol):
        code = generate_lean4(protocol)
        # Pattern: "  | constructor_name"
        assert re.search(r"  \| \w+", code)

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_theorem_uses_forall_quantifier(self, name, protocol):
        code = generate_lean4(protocol)
        assert "∀" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_theorem_references_protocol_roles(self, name, protocol):
        code = generate_lean4(protocol)
        assert f"{name}_roles" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_theorem_references_all_steps(self, name, protocol):
        code = generate_lean4(protocol)
        assert f"{name}_all_steps" in code

    def test_step_uses_dot_syntax_for_kind(self):
        code = generate_lean4(DelegateTask)
        # Lean 4 dot syntax: .task_request not MessageKind.task_request
        assert ".task_request" in code
        assert "MessageKind.task_request" not in code

    def test_roles_are_quoted_strings(self):
        code = generate_lean4(DelegateTask)
        assert '"regina"' in code
        assert '"worker"' in code

    def test_step_fields_use_walrus_syntax(self):
        code = generate_lean4(DelegateTask)
        # Lean 4 anonymous constructor: { field := value }
        assert "sender :=" in code
        assert "receiver :=" in code
        assert "message_kind :=" in code


# ============================================================
# 5. Only used message kinds are generated
# ============================================================


class TestOnlyUsedKinds:
    def test_simple_task_excludes_audit_kinds(self):
        code = generate_lean4(SimpleTask)
        # SimpleTask only uses task_request and task_result
        assert "audit_request" not in code
        assert "audit_verdict" not in code

    def test_simple_task_excludes_plan_kinds(self):
        code = generate_lean4(SimpleTask)
        assert "plan_request" not in code
        assert "plan_proposal" not in code

    def test_research_flow_includes_research_kinds(self):
        code = generate_lean4(ResearchFlow)
        assert "research_query" in code
        assert "research_report" in code

    def test_research_flow_excludes_task_result(self):
        code = generate_lean4(ResearchFlow)
        assert "task_result" not in code

    def test_architect_flow_includes_plan_kinds(self):
        code = generate_lean4(ArchitectFlow)
        assert "plan_request" in code
        assert "plan_proposal" in code
        assert "plan_decision" in code

    def test_custom_single_kind_protocol(self):
        proto = make_custom_protocol(kind=MessageKind.SHUTDOWN_REQUEST)
        code = generate_lean4(proto)
        assert "shutdown_request" in code
        # No other kinds
        assert "task_request" not in code
        assert "audit_request" not in code


# ============================================================
# 6. Multi-protocol generation
# ============================================================


class TestMultiProtocolGeneration:
    def test_single_message_kind_inductive(self):
        """Multi-generation shares a single MessageKind inductive."""
        code = generate_lean4_multi([DelegateTask, ResearchFlow])
        count = code.count("inductive MessageKind where")
        assert count == 1

    def test_all_protocols_present_in_output(self):
        protocols = [DelegateTask, ArchitectFlow, ResearchFlow, SimpleTask]
        code = generate_lean4_multi(protocols)
        for proto in protocols:
            assert f"Protocol: {proto.name}" in code

    def test_types_shared_section_label(self):
        code = generate_lean4_multi([SimpleTask, DelegateTask])
        assert "Types (shared)" in code

    def test_theorems_for_each_protocol(self):
        code = generate_lean4_multi([SimpleTask, ResearchFlow])
        assert "theorem SimpleTask_senders_valid" in code
        assert "theorem ResearchFlow_senders_valid" in code

    def test_all_combined_kinds_included(self):
        # SimpleTask: task_request, task_result
        # ResearchFlow: research_query, research_report, audit_request, audit_verdict
        code = generate_lean4_multi([SimpleTask, ResearchFlow])
        assert "task_request" in code
        assert "research_query" in code
        assert "audit_request" in code

    def test_generated_header_lists_all_protocol_names(self):
        code = generate_lean4_multi([SimpleTask, DelegateTask])
        assert "SimpleTask" in code
        assert "DelegateTask" in code

    def test_empty_raises_value_error(self):
        with pytest.raises(ValueError):
            generate_lean4_multi([])


# ============================================================
# 7. Custom / non-standard protocols
# ============================================================


class TestCustomProtocol:
    def test_custom_flat_protocol_generates_correctly(self):
        proto = make_custom_protocol(name="MyProto", roles=("sender", "receiver"))
        code = generate_lean4(proto)
        assert "Protocol: MyProto" in code
        assert "def MyProto_roles" in code
        assert "def MyProto_all_steps" in code
        assert "theorem MyProto_senders_valid" in code

    def test_single_kind_generates_single_constructor(self):
        proto = make_custom_protocol(kind=MessageKind.DM)
        gen = Lean4Generator()
        code = gen.generate_message_kind(_used_message_kinds(proto))
        assert "dm" in code
        assert code.count("| ") == 1

    def test_custom_choice_protocol_with_special_branch_names(self):
        proto = Protocol(
            name="SpecialNames",
            roles=("a", "b"),
            elements=(
                ProtocolChoice(
                    decider="a",
                    branches={
                        "my-branch": (
                            ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.DM),
                        ),
                        "other branch": (
                            ProtocolStep(sender="b", receiver="a", message_kind=MessageKind.BROADCAST),
                        ),
                    },
                ),
            ),
        )
        code = generate_lean4(proto)
        # Hyphens and spaces converted
        assert "SpecialNames_branch_my_branch" in code
        assert "SpecialNames_branch_other_branch" in code
        # Original names not present as identifiers
        assert "branch_my-branch" not in code

    def test_three_roles_custom_protocol(self):
        proto = Protocol(
            name="ThreeRoles",
            roles=("a", "b", "c"),
            elements=(
                ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.TASK_REQUEST),
                ProtocolStep(sender="b", receiver="c", message_kind=MessageKind.AUDIT_REQUEST),
                ProtocolStep(sender="c", receiver="a", message_kind=MessageKind.AUDIT_VERDICT),
            ),
        )
        code = generate_lean4(proto)
        assert '"a"' in code
        assert '"b"' in code
        assert '"c"' in code
        assert "theorem ThreeRoles_min_roles" in code


# ============================================================
# 8. Lean4Verifier - mocked subprocess
# ============================================================


class TestLean4VerifierMocked:
    def test_verify_code_calls_subprocess_with_lean_json(self):
        """verify_code uses lean --json."""
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(
                    stdout="",
                    stderr="",
                    returncode=0,
                )
                verifier = Lean4Verifier(timeout=5)
                result = verifier.verify_code("-- lean code")
                assert result == []
                mock_run.assert_called_once()
                call_args = mock_run.call_args[0][0]
                assert "lean" in call_args
                assert "--json" in call_args

    def test_verify_code_parses_json_output(self):
        """JSON lines from lean output are parsed into dicts."""
        import json

        msg = {"severity": "info", "data": "loaded"}
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(
                    stdout=json.dumps(msg) + "\n",
                    stderr="",
                    returncode=0,
                )
                verifier = Lean4Verifier()
                result = verifier.verify_code("-- lean code")
                assert result == [msg]

    def test_verify_code_ignores_invalid_json_lines(self):
        """Non-JSON lines (e.g. progress output) are silently skipped."""
        valid_json = '{"severity": "info", "data": "ok"}'
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(
                    stdout="not json\n" + valid_json + "\nalso not json\n",
                    stderr="",
                    returncode=0,
                )
                verifier = Lean4Verifier()
                result = verifier.verify_code("-- code")
                assert len(result) == 1
                assert result[0]["severity"] == "info"

    def test_verify_code_raises_timeout_error(self):
        """subprocess.TimeoutExpired is converted to TimeoutError."""
        import subprocess

        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.side_effect = subprocess.TimeoutExpired(cmd="lean", timeout=5)
                verifier = Lean4Verifier(timeout=5)
                with pytest.raises(TimeoutError, match="timed out"):
                    verifier.verify_code("-- code")

    def test_verify_code_cleans_up_temp_file(self):
        """Temp file is deleted even on success."""
        import tempfile

        created_files = []

        original_ntf = tempfile.NamedTemporaryFile

        def capturing_ntf(*args, **kwargs):
            f = original_ntf(*args, **kwargs)
            created_files.append(f.name)
            return f

        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(stdout="", stderr="", returncode=0)
                with mock.patch("tempfile.NamedTemporaryFile", side_effect=capturing_ntf):
                    verifier = Lean4Verifier()
                    verifier.verify_code("-- code")

        # All created temp files should be deleted
        import os

        for path in created_files:
            assert not os.path.exists(path), f"Temp file not cleaned up: {path}"

    def test_verify_protocol_returns_report_on_success(self):
        """verify_protocol builds a VerificationReport when all theorems pass."""
        code = generate_lean4(SimpleTask)

        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                # Empty output = no errors = all proved
                mock_run.return_value = mock.Mock(stdout="", stderr="", returncode=0)
                verifier = Lean4Verifier()
                report = verifier.verify_protocol(SimpleTask)

        assert isinstance(report, VerificationReport)
        assert report.protocol_name == "SimpleTask"
        assert report.all_proved is True
        assert report.total_count == len(FLAT_PROPERTIES)

    def test_verify_protocol_flat_uses_flat_properties(self):
        """Flat protocol verification checks exactly FLAT_PROPERTIES."""
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(stdout="", stderr="", returncode=0)
                verifier = Lean4Verifier()
                report = verifier.verify_protocol(SimpleTask)

        property_names = {r.property_name for r in report.results}
        expected = {p.value for p in FLAT_PROPERTIES}
        assert property_names == expected

    def test_verify_protocol_choice_uses_all_properties(self):
        """Choice protocol verification includes choice-specific properties."""
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(stdout="", stderr="", returncode=0)
                verifier = Lean4Verifier()
                report = verifier.verify_protocol(ArchitectFlow)

        property_names = {r.property_name for r in report.results}
        assert VerificationProperty.BRANCHES_NON_EMPTY.value in property_names
        assert VerificationProperty.DECIDER_IN_ROLES.value in property_names

    def test_verify_protocol_marks_failed_when_errors(self):
        """When lean reports errors matching a theorem, proved=False."""
        import json

        error_msg = {
            "severity": "error",
            "data": "SimpleTask_no_self_loop failed",
        }
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(
                    stdout=json.dumps(error_msg) + "\n",
                    stderr="",
                    returncode=1,
                )
                verifier = Lean4Verifier()
                report = verifier.verify_protocol(SimpleTask)

        # The theorem specifically mentioned in the error should be not proved
        self_loop_result = next(
            r for r in report.results if r.property_name == "no_self_loop"
        )
        assert self_loop_result.proved is False
        assert self_loop_result.error is not None

    def test_verify_protocol_uses_supplied_properties(self):
        """Custom properties list is respected."""
        with mock.patch(
            "cervellaswarm_lingua_universale.lean4_bridge.lean4_available",
            return_value=True,
        ):
            with mock.patch("subprocess.run") as mock_run:
                mock_run.return_value = mock.Mock(stdout="", stderr="", returncode=0)
                verifier = Lean4Verifier()
                report = verifier.verify_protocol(
                    SimpleTask,
                    properties=[VerificationProperty.NON_EMPTY],
                )

        assert report.total_count == 1
        assert report.results[0].property_name == "non_empty"


# ============================================================
# 9. VerificationReport round-trip
# ============================================================


class TestVerificationReportRoundTrip:
    def test_report_preserves_lean_code(self):
        code = generate_lean4(DelegateTask)
        result = VerificationResult(
            property_name="non_empty",
            proved=True,
            lean_theorem="theorem t : True := by decide",
        )
        report = VerificationReport(
            protocol_name="DelegateTask",
            results=(result,),
            lean_code=code,
        )
        assert report.lean_code == code

    def test_proved_count_matches_results(self):
        results = (
            VerificationResult(
                property_name="non_empty",
                proved=True,
                lean_theorem="theorem t : True := by decide",
            ),
            VerificationResult(
                property_name="no_self_loop",
                proved=False,
                lean_theorem="theorem t2 : True := by decide",
                error="failed",
            ),
        )
        report = VerificationReport(
            protocol_name="Test",
            results=results,
            lean_code="-- code",
        )
        assert report.proved_count == 1
        assert report.total_count == 2
        assert report.all_proved is False

    def test_empty_results_report_properties(self):
        report = VerificationReport(
            protocol_name="Empty",
            results=(),
            lean_code="-- code",
        )
        assert report.proved_count == 0
        assert report.total_count == 0
        assert report.all_proved is False


# ============================================================
# 10. Protocol-specific code correctness
# ============================================================


class TestProtocolSpecificCorrectness:
    def test_delegate_task_roles_in_output(self):
        code = generate_lean4(DelegateTask)
        assert '"regina"' in code
        assert '"worker"' in code
        assert '"guardiana"' in code

    def test_delegate_task_four_steps(self):
        gen = Lean4Generator()
        code = gen.generate_steps(DelegateTask)
        # 4 steps: task_request, task_result, audit_request, audit_verdict
        assert code.count("sender :=") == 4

    def test_research_flow_three_roles(self):
        code = generate_lean4(ResearchFlow)
        assert '"researcher"' in code
        assert '"guardiana"' in code

    def test_architect_flow_four_roles(self):
        code = generate_lean4(ArchitectFlow)
        assert '"architect"' in code
        assert '"guardiana"' in code

    def test_simple_task_two_roles_only(self):
        code = generate_lean4(SimpleTask)
        # Only regina and worker
        assert '"regina"' in code
        assert '"worker"' in code
        assert '"guardiana"' not in code
        assert '"architect"' not in code

    def test_architect_flow_branches_in_output(self):
        code = generate_lean4(ArchitectFlow)
        assert "ArchitectFlow_branch_approve" in code
        assert "ArchitectFlow_branch_reject" in code

    def test_approve_branch_has_five_steps(self):
        gen = Lean4Generator()
        branches_code = gen.generate_branches(ArchitectFlow)
        # Extract approve branch
        approve_section = branches_code.split("ArchitectFlow_branch_reject")[0]
        step_count = approve_section.count("sender :=")
        assert step_count == 5

    def test_reject_branch_has_two_steps(self):
        gen = Lean4Generator()
        branches_code = gen.generate_branches(ArchitectFlow)
        # Extract reject branch (after approve)
        reject_section = branches_code.split("ArchitectFlow_branch_reject")[1]
        step_count = reject_section.count("sender :=")
        assert step_count == 2


# ============================================================
# 11. Generate all standard protocols smoke test
# ============================================================


class TestStandardProtocolSmoke:
    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_generate_does_not_raise(self, name, protocol):
        code = generate_lean4(protocol)
        assert isinstance(code, str)
        assert len(code) > 0

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_generated_code_contains_protocol_roles_def(self, name, protocol):
        code = generate_lean4(protocol)
        assert f"def {name}_roles" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_generated_code_contains_all_steps_def(self, name, protocol):
        code = generate_lean4(protocol)
        assert f"def {name}_all_steps" in code

    @pytest.mark.parametrize("name,protocol", STANDARD_PROTOCOLS.items())
    def test_generated_code_contains_five_or_more_theorems(self, name, protocol):
        gen = Lean4Generator()
        code = gen.generate_theorems(protocol)
        count = len(re.findall(r"^theorem ", code, re.MULTILINE))
        assert count >= 5

    @pytest.mark.parametrize("name", ["DelegateTask", "ResearchFlow", "SimpleTask"])
    def test_flat_protocols_do_not_contain_branch_defs(self, name):
        proto = STANDARD_PROTOCOLS[name]
        gen = Lean4Generator()
        branches = gen.generate_branches(proto)
        assert branches == ""


# ============================================================
# 12. Edge cases
# ============================================================


class TestEdgeCases:
    def test_protocol_with_single_step_generates_valid_code(self):
        proto = Protocol(
            name="OneStep",
            roles=("a", "b"),
            elements=(
                ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.DM),
            ),
        )
        code = generate_lean4(proto)
        assert "def OneStep_all_steps" in code
        assert ".dm" in code
        assert "theorem OneStep_non_empty" in code

    def test_protocol_with_many_roles(self):
        proto = Protocol(
            name="ManyRoles",
            roles=("a", "b", "c", "d", "e"),
            elements=(
                ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.TASK_REQUEST),
                ProtocolStep(sender="b", receiver="c", message_kind=MessageKind.TASK_RESULT),
            ),
        )
        code = generate_lean4(proto)
        for role in ("a", "b", "c", "d", "e"):
            assert f'"{role}"' in code

    def test_branch_name_with_multiple_hyphens(self):
        proto = Protocol(
            name="MultiHyphen",
            roles=("a", "b"),
            elements=(
                ProtocolChoice(
                    decider="a",
                    branches={
                        "first-branch-name": (
                            ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.DM),
                        ),
                    },
                ),
            ),
        )
        code = generate_lean4(proto)
        assert "branch_first_branch_name" in code

    def test_multi_protocol_with_same_kind_used_once(self):
        """When both protocols use TASK_REQUEST, it appears once in inductive."""
        code = generate_lean4_multi([SimpleTask, DelegateTask])
        # Count occurrences in inductive block only
        inductive_block = code.split("structure ProtocolStep")[0]
        count = inductive_block.count("task_request")
        assert count == 1

    def test_generate_lean4_multi_with_choice_protocol(self):
        code = generate_lean4_multi([SimpleTask, ArchitectFlow])
        assert "ArchitectFlow_branch_approve" in code
        assert "theorem ArchitectFlow_branches_non_empty" in code

    def test_custom_protocol_name_with_numbers(self):
        proto = Protocol(
            name="Proto123",
            roles=("a", "b"),
            elements=(
                ProtocolStep(sender="a", receiver="b", message_kind=MessageKind.DM),
            ),
        )
        code = generate_lean4(proto)
        assert "def Proto123_roles" in code
        assert "theorem Proto123_senders_valid" in code


# ============================================================
# Helper import for used_message_kinds (needed in tests above)
# ============================================================

from cervellaswarm_lingua_universale.lean4_bridge import _used_message_kinds  # noqa: E402
