# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CervellaSwarm Contributors
"""Symbol Extractor for Repository Mapping.

This module extracts symbols (functions, classes, types, interfaces) from AST
generated by TreesitterParser. It provides concise signatures without function
bodies, perfect for repository mapping with minimal token usage.

Usage:
    from treesitter_parser import TreesitterParser
    from symbol_extractor import SymbolExtractor

    parser = TreesitterParser()
    extractor = SymbolExtractor(parser)
    symbols = extractor.extract_symbols("app/main.py")

    for symbol in symbols:
        print(f"{symbol.name}: {symbol.signature}")

Supported Languages:
    - Python: functions, classes, type aliases
    - TypeScript/TSX: functions, interfaces, type aliases
    - JavaScript/JSX: functions, classes

Author: Cervella Backend
Version: 3.0.0 (F1.1 Split)
Date: 2026-02-02
"""

__version__ = "3.0.0"
__version_date__ = "2026-02-02"
__changelog__ = """
v3.0.0 (2026-02-02) - F1.1 Split (Tech Debt Cleanup)
    - Split into multiple modules for maintainability
    - Extracted PythonExtractor to python_extractor.py
    - Extracted TypeScriptExtractor to typescript_extractor.py
    - SymbolExtractor now uses composition pattern
    - Reduced from 1069 lines to ~370 lines
    - All tests pass, full backward compatibility maintained

v2.3.0 (2026-02-02) - F1.1 LRU Cache (H3 Memory Leak Fix)
    - Replaced unbounded dict cache with LRU cache (maxsize=1000)
    - Imported SymbolCache from symbol_cache.py
    - Cache now evicts least recently used entries automatically
    - Added hit/miss statistics tracking
    - Fixes H3 from Code Review S327

v2.2.0 (2026-01-19) - W2.5-C Caching
    - Added _symbol_cache for mtime-based symbol caching (REQ-09)
    - Added clear_cache(), invalidate_cache(), get_cache_stats() methods
    - extract_symbols() now uses cache for repeated calls

v2.1.0 (2026-01-19) - W2.5-B TypeScript Reference Extraction
    - Added TS_BUILTINS frozenset for TypeScript/JavaScript builtins filtering
    - Added _extract_typescript_references() for TS/JS code analysis
    - Added _extract_ts_module_level_references() for import extraction
    - TypeScript symbols now include references (REQ-07 implemented)
    - JavaScript symbols now include references (bonus)
    - Added class_declaration support for TypeScript
    - Supports: function calls, method calls, imports, class extends, type annotations

v2.0.0 (2026-01-19) - W2.5-A Python Reference Extraction
    - Added _extract_python_references() for Python code analysis
    - Symbol.references now populated during extract_symbols()
    - Supports: function calls, method calls, imports, inheritance, type annotations
    - Filters Python builtins (PYTHON_BUILTINS set)
    - REQ-01 to REQ-06 implemented
"""

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from tree_sitter import Node

from .treesitter_parser import TreesitterParser
from .symbol_cache import SymbolCache
from .symbol_types import Symbol
from .language_builtins import PYTHON_BUILTINS, TS_BUILTINS
from .python_extractor import PythonExtractor
from .typescript_extractor import TypeScriptExtractor

# Configure logging
logger = logging.getLogger(__name__)


# Re-export Symbol for backward compatibility
__all__ = ['Symbol', 'SymbolExtractor', 'extract_symbols', 'PYTHON_BUILTINS', 'TS_BUILTINS']


class SymbolExtractor:
    """Extract symbols from source code using tree-sitter.

    This class uses TreesitterParser to parse source files and extract
    symbol definitions (functions, classes, interfaces, types) with their
    signatures but without implementation details.

    Attributes:
        parser: TreesitterParser instance for parsing files
    """

    def __init__(self, parser: TreesitterParser, cache_maxsize: int = 1000):
        """Initialize extractor with a parser.

        Args:
            parser: TreesitterParser instance to use for parsing
            cache_maxsize: Maximum number of files to cache (default 1000).
                          LRU eviction when exceeded. Fixes H3 memory leak.

        Attributes:
            parser: TreesitterParser instance for parsing files
            _symbol_cache: LRU cache of extracted symbols (SymbolCache)
            _python_extractor: PythonExtractor for Python symbol extraction
            _ts_extractor: TypeScriptExtractor for TS/JS symbol extraction
        """
        self.parser = parser
        self._symbol_cache = SymbolCache(maxsize=cache_maxsize)
        self._python_extractor = PythonExtractor()
        self._ts_extractor = TypeScriptExtractor()
        logger.debug(f"SymbolExtractor initialized with cache maxsize={cache_maxsize}")

    # Delegation methods for backward compatibility (private methods)
    def _extract_python_references(self, node: Node) -> List[str]:
        """Delegate to PythonExtractor. Kept for backward compatibility."""
        return self._python_extractor.extract_python_references(node)

    def _extract_module_level_references(self, root_node: Node) -> List[str]:
        """Delegate to PythonExtractor. Kept for backward compatibility."""
        return self._python_extractor.extract_module_level_references(root_node)

    def _extract_typescript_references(self, node: Node) -> List[str]:
        """Delegate to TypeScriptExtractor. Kept for backward compatibility."""
        return self._ts_extractor.extract_typescript_references(node)

    def _extract_ts_module_level_references(self, root_node: Node) -> List[str]:
        """Delegate to TypeScriptExtractor. Kept for backward compatibility."""
        return self._ts_extractor.extract_ts_module_level_references(root_node)

    def extract_symbols(self, file_path: str) -> List[Symbol]:
        """Extract all symbols from a file.

        Uses caching to avoid re-extraction if file hasn't changed (REQ-09).
        Cache key is (absolute_path, mtime).

        Graceful degradation (REQ-10): Returns empty list on any failure
        (file not found, parse error, unsupported language) instead of
        raising exceptions.

        Args:
            file_path: Path to source file

        Returns:
            List of Symbol objects found in the file.
            Returns [] if file doesn't exist, can't be parsed, or
            language is unsupported.

        Example:
            >>> extractor = SymbolExtractor(parser)
            >>> symbols = extractor.extract_symbols("app/auth.py")
            >>> print([s.name for s in symbols])
            ['login', 'logout', 'verify_credentials']
            >>> extractor.extract_symbols("/nonexistent.py")  # Returns []
            []
        """
        # REQ-09: Check cache first
        abs_path = str(Path(file_path).resolve())
        try:
            current_mtime = os.path.getmtime(abs_path)
        except OSError:
            current_mtime = 0.0

        # Try cache first (LRU cache handles mtime validation internally)
        cached_symbols = self._symbol_cache.get(abs_path, current_mtime)
        if cached_symbols is not None:
            logger.debug(f"Using cached symbols for: {file_path}")
            return cached_symbols

        # REQ-10: Graceful degradation - handle parse failures
        try:
            tree = self.parser.parse_file(file_path)
        except FileNotFoundError:
            logger.warning(f"File not found: {file_path}, no symbols extracted")
            return []
        except Exception as e:
            logger.warning(f"Failed to parse {file_path}: {e}, no symbols extracted")
            return []

        if tree is None:
            logger.warning(f"Failed to parse {file_path}, no symbols extracted")
            return []

        # Detect language
        try:
            language = self.parser.detect_language(file_path)
        except ValueError as e:
            logger.warning(f"Cannot extract symbols from {file_path}: {e}")
            return []

        # Extract symbols based on language (delegate to specialized extractors)
        if language == "python":
            symbols = self._python_extractor.extract_python_symbols(tree, file_path)
        elif language in ["typescript", "tsx"]:
            symbols = self._ts_extractor.extract_typescript_symbols(tree, file_path)
        elif language in ["javascript", "jsx"]:
            symbols = self._ts_extractor.extract_javascript_symbols(tree, file_path)
        else:
            logger.warning(f"Symbol extraction not implemented for: {language}")
            symbols = []

        # REQ-09: Store in LRU cache (with automatic eviction)
        if current_mtime > 0:
            self._symbol_cache.set(abs_path, current_mtime, symbols)
            logger.debug(f"Cached {len(symbols)} symbols for: {file_path}")

        return symbols


    def extract_signature(self, symbol: Symbol) -> str:
        """Extract concise signature from symbol.

        This is already done during symbol creation, so just return
        the stored signature.

        Args:
            symbol: Symbol object

        Returns:
            Concise signature string

        Example:
            >>> symbol = Symbol(name="login", ...)
            >>> extractor.extract_signature(symbol)
            'def login(username: str, password: str) -> bool'
        """
        return symbol.signature

    def extract_references(self, symbol: Symbol, tree=None) -> List[str]:
        """Extract references (calls to other functions) from symbol.

        Note: As of W2.5, references are extracted during symbol creation
        and stored in symbol.references. This method returns the pre-computed
        references.

        Args:
            symbol: Symbol to analyze
            tree: (Deprecated) No longer needed, kept for API compatibility

        Returns:
            List of referenced symbol names
        """
        # W2.5: References are now extracted during symbol creation
        return symbol.references

    def clear_cache(self) -> None:
        """Clear all cached symbols.

        Call this to free memory or when you want to force re-extraction
        of all files.

        Example:
            >>> extractor.clear_cache()
        """
        self._symbol_cache.clear()
        logger.debug("Symbol cache cleared")

    def invalidate_cache(self, file_path: str) -> None:
        """Invalidate cache for a specific file.

        Call this when you know a file has changed and want to force
        re-extraction on next extract_symbols() call.

        Args:
            file_path: Path to the file to invalidate

        Example:
            >>> extractor.invalidate_cache("app.py")
        """
        abs_path = str(Path(file_path).resolve())
        if self._symbol_cache.invalidate(abs_path):
            logger.debug(f"Invalidated cache for: {file_path}")

    def get_cache_stats(self) -> Dict[str, int]:
        """Get statistics about cache usage.

        Returns:
            Dictionary with cache statistics:
            - cached_files: Number of files with cached symbols
            - cached_symbols: Total number of cached symbols
            - maxsize: Maximum cache size (LRU limit)
            - hits: Number of cache hits
            - misses: Number of cache misses
            - hit_rate: Hit rate percentage (0-100)

        Example:
            >>> stats = extractor.get_cache_stats()
            >>> print(stats)
            {'cached_files': 10, 'cached_symbols': 156, 'maxsize': 1000, ...}
        """
        return self._symbol_cache.get_stats()


# Convenience function for simple usage
def extract_symbols(file_path: str) -> List[Symbol]:
    """Extract symbols from a file without managing instances.

    This is a convenience function for one-off extraction. For repeated
    extraction, create a SymbolExtractor instance to benefit from caching.

    Args:
        file_path: Path to source file

    Returns:
        List of Symbol objects

    Example:
        >>> from symbol_extractor import extract_symbols
        >>> symbols = extract_symbols("app.py")
        >>> for s in symbols:
        ...     print(s.signature)
    """
    parser = TreesitterParser()
    extractor = SymbolExtractor(parser)
    return extractor.extract_symbols(file_path)


if __name__ == "__main__":
    # Simple CLI for testing
    import sys

    if len(sys.argv) < 2:
        print(f"Usage: python {sys.argv[0]} <file_path>")
        print("\nExtract symbols from a source file")
        sys.exit(1)

    # Enable debug logging
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    file_path = sys.argv[1]

    try:
        parser = TreesitterParser()
        extractor = SymbolExtractor(parser)
        symbols = extractor.extract_symbols(file_path)

        if symbols:
            print(f"\n✅ Extracted {len(symbols)} symbols from: {file_path}\n")

            # Group by type
            by_type = {}
            for symbol in symbols:
                if symbol.type not in by_type:
                    by_type[symbol.type] = []
                by_type[symbol.type].append(symbol)

            # Display grouped
            for sym_type, type_symbols in sorted(by_type.items()):
                print(f"\n{sym_type.upper()}S ({len(type_symbols)}):")
                for symbol in type_symbols:
                    print(f"  Line {symbol.line:4d}: {symbol.signature}")
                    if symbol.docstring:
                        # Show first line of docstring
                        first_line = symbol.docstring.split("\n")[0]
                        print(f"             # {first_line}")

        else:
            print(f"\n⚠️  No symbols found in: {file_path}")

    except FileNotFoundError:
        print(f"\n❌ File not found: {file_path}")
        sys.exit(1)
    except ValueError as e:
        print(f"\n❌ {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
