# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CervellaSwarm Contributors
"""TypeScript/JavaScript Symbol Extractor.

This module extracts TypeScript/JavaScript-specific symbols (functions, classes,
interfaces, types) from AST nodes generated by tree-sitter. Part of the F1.1
tech debt cleanup split.

Usage:
    from typescript_extractor import TypeScriptExtractor
    extractor = TypeScriptExtractor()
    symbols = extractor.extract_typescript_symbols(tree, "app.ts")

Author: Cervella Backend (F1.1 Split)
Version: 1.1.0
Date: 2026-03-29
v1.1.0 - S493: Dispatch dict refactoring (CC 30+->6), dedup import extraction
"""

__version__ = "1.1.0"
__version_date__ = "2026-03-29"

import logging
from typing import List

from tree_sitter import Node

from .symbol_types import Symbol
from .language_builtins import TS_BUILTINS

logger = logging.getLogger(__name__)


class TypeScriptExtractor:
    """Extract TypeScript/JavaScript symbols from tree-sitter AST.

    This class handles all TypeScript/JavaScript-specific symbol extraction:
    - Functions
    - Classes
    - Interfaces
    - Type aliases
    - Reference extraction (imports, calls, inheritance, etc.)

    Attributes:
        None (stateless extractor)
    """

    def __init__(self):
        """Initialize TypeScript/JavaScript extractor."""
        self._ref_handlers = {
            "call_expression": self._handle_call_expr_ref,
            "class_declaration": self._handle_class_heritage_ref,
            "class": self._handle_class_heritage_ref,
            "type_annotation": self._handle_type_annotation_ref,
            "type_identifier": self._handle_type_identifier_ref,
        }
        logger.debug("TypeScriptExtractor initialized")

    # --- Reference handler methods ---

    def _handle_call_expr_ref(self, n: Node, refs: set) -> None:
        """Function calls: myFunc() or obj.method()."""
        func_node = n.child_by_field_name("function")
        if not func_node:
            return
        if func_node.type == "identifier":
            name = func_node.text.decode()
            if name not in TS_BUILTINS:
                refs.add(name)
        elif func_node.type == "member_expression":
            prop_node = func_node.child_by_field_name("property")
            if prop_node and prop_node.type == "property_identifier":
                method_name = prop_node.text.decode()
                if method_name not in TS_BUILTINS:
                    refs.add(method_name)
            obj_node = func_node.child_by_field_name("object")
            if obj_node and obj_node.type == "identifier":
                obj_name = obj_node.text.decode()
                if obj_name not in TS_BUILTINS:
                    refs.add(obj_name)

    def _handle_class_heritage_ref(self, n: Node, refs: set) -> None:
        """Class inheritance: class Child extends Parent."""
        for child in n.children:
            if child.type == "class_heritage":
                for heritage_child in child.children:
                    if heritage_child.type == "extends_clause":
                        for ext_child in heritage_child.children:
                            if ext_child.type == "identifier":
                                base_name = ext_child.text.decode()
                                if base_name not in TS_BUILTINS:
                                    refs.add(base_name)
                            elif ext_child.type == "member_expression":
                                prop = ext_child.child_by_field_name("property")
                                if prop:
                                    refs.add(prop.text.decode())

    def _handle_type_annotation_ref(self, n: Node, refs: set) -> None:
        """Type annotations: param: MyType, const x: MyType."""
        for child in n.children:
            if child.type == "type_identifier":
                type_name = child.text.decode()
                if type_name not in TS_BUILTINS:
                    refs.add(type_name)
            elif child.type == "generic_type":
                type_id = child.child_by_field_name("name")
                if type_id and type_id.type == "type_identifier":
                    type_name = type_id.text.decode()
                    if type_name not in TS_BUILTINS:
                        refs.add(type_name)
                type_args = child.child_by_field_name("type_arguments")
                if type_args:
                    for arg in type_args.children:
                        if arg.type == "type_identifier":
                            arg_name = arg.text.decode()
                            if arg_name not in TS_BUILTINS:
                                refs.add(arg_name)

    def _handle_type_identifier_ref(self, n: Node, refs: set) -> None:
        """Standalone type_identifier (return types, etc.)."""
        type_name = n.text.decode()
        if type_name not in TS_BUILTINS:
            refs.add(type_name)

    # --- Public API (unchanged) ---

    def extract_typescript_references(self, node: Node) -> List[str]:
        """Extract all references from a TypeScript/JavaScript AST node.

        Extracts function calls, method calls, class inheritance, and type
        annotations from the given node and its children.

        Args:
            node: Tree-sitter Node to analyze (typically function/class body)

        Returns:
            List of unique reference names (excluding TS builtins)

        Covers (REQ-07):
            - Function calls: myFunc()
            - Method calls: obj.method()
            - Class extends: class Child extends Parent
            - Type annotations: param: MyType
        """
        references = set()
        handlers = self._ref_handlers

        def extract_from_node(n: Node) -> None:
            handler = handlers.get(n.type)
            if handler:
                handler(n, references)
            for child in n.children:
                extract_from_node(child)

        extract_from_node(node)
        return sorted(references)

    @staticmethod
    def _add_identifier(node: Node, refs: set) -> None:
        """Add node's text to refs if it's not a TS builtin."""
        name = node.text.decode()
        if name not in TS_BUILTINS:
            refs.add(name)

    def _extract_named_imports(self, node: Node, refs: set) -> None:
        """Extract identifiers from a named_imports node ({A, B, C})."""
        for spec in node.children:
            if spec.type == "import_specifier":
                name_node = spec.child_by_field_name("name")
                if name_node:
                    self._add_identifier(name_node, refs)
                else:
                    for spec_child in spec.children:
                        if spec_child.type == "identifier":
                            self._add_identifier(spec_child, refs)
                            break

    def _extract_import_refs(self, n: Node, refs: set) -> None:
        """Extract from a single import statement node."""
        for child in n.children:
            if child.type == "import_clause":
                for clause_child in child.children:
                    if clause_child.type == "identifier":
                        self._add_identifier(clause_child, refs)
                    elif clause_child.type == "named_imports":
                        self._extract_named_imports(clause_child, refs)
                    elif clause_child.type == "namespace_import":
                        for ns_child in clause_child.children:
                            if ns_child.type == "identifier":
                                self._add_identifier(ns_child, refs)

    def extract_ts_module_level_references(self, root_node: Node) -> List[str]:
        """Extract module-level references (imports) from TypeScript/JS AST.

        These are references that apply to the entire file, not specific symbols.

        Args:
            root_node: Root node of the parsed tree (program node)

        Returns:
            List of import references (imported names)
        """
        references = set()

        def extract_imports(n: Node) -> None:
            if n.type == "import_statement":
                self._extract_import_refs(n, references)
            for child in n.children:
                extract_imports(child)

        for child in root_node.children:
            extract_imports(child)

        return sorted(references)

    def extract_typescript_symbols(self, tree, file_path: str) -> List[Symbol]:
        """Extract symbols from TypeScript/TSX AST using direct traversal.

        Args:
            tree: Parsed tree-sitter Tree
            file_path: Source file path

        Returns:
            List of Symbol objects
        """
        symbols = []
        module_refs = self.extract_ts_module_level_references(tree.root_node)

        def traverse(node: Node) -> None:
            if node.type == "function_declaration":
                name_node = node.child_by_field_name("name")
                params_node = node.child_by_field_name("parameters")

                if name_node:
                    name = name_node.text.decode()
                    params = params_node.text.decode() if params_node else "()"
                    signature = f"function {name}{params}"

                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbols.append(Symbol(
                        name=name,
                        type="function",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    ))

            elif node.type == "class_declaration":
                name_node = node.child_by_field_name("name")

                if name_node:
                    name = name_node.text.decode()
                    signature = f"class {name}"
                    for child in node.children:
                        if child.type == "class_heritage":
                            heritage_text = child.text.decode()
                            signature = f"class {name} {heritage_text}"
                            break

                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbols.append(Symbol(
                        name=name,
                        type="class",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    ))

            elif node.type == "interface_declaration":
                name_node = node.child_by_field_name("name")
                body_node = node.child_by_field_name("body")

                if name_node:
                    name = name_node.text.decode()
                    body = body_node.text.decode() if body_node else "{ }"
                    if len(body) > 100:
                        body = "{ ... }"
                    signature = f"interface {name} {body}"

                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbols.append(Symbol(
                        name=name,
                        type="interface",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    ))

            elif node.type == "type_alias_declaration":
                name_node = node.child_by_field_name("name")

                if name_node:
                    name = name_node.text.decode()
                    signature = f"type {name} = ..."

                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbols.append(Symbol(
                        name=name,
                        type="type",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    ))

            for child in node.children:
                traverse(child)

        traverse(tree.root_node)
        logger.debug(f"Extracted {len(symbols)} TypeScript symbols from {file_path}")
        return symbols

    def extract_javascript_symbols(self, tree, file_path: str) -> List[Symbol]:
        """Extract symbols from JavaScript/JSX AST using direct traversal.

        Delegates to extract_typescript_symbols -- JS is a subset of TS,
        and interface/type_alias nodes don't exist in JS ASTs so those
        branches never fire. S493: dedup -60 LOC.

        Args:
            tree: Parsed tree-sitter Tree
            file_path: Source file path

        Returns:
            List of Symbol objects
        """
        return self.extract_typescript_symbols(tree, file_path)
