# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CervellaSwarm Contributors
"""TypeScript/JavaScript Symbol Extractor.

This module extracts TypeScript/JavaScript-specific symbols (functions, classes,
interfaces, types) from AST nodes generated by tree-sitter. Part of the F1.1
tech debt cleanup split.

Usage:
    from typescript_extractor import TypeScriptExtractor
    extractor = TypeScriptExtractor()
    symbols = extractor.extract_typescript_symbols(tree, "app.ts")

Author: Cervella Backend (F1.1 Split)
Version: 1.0.0
Date: 2026-02-02
"""

__version__ = "1.0.0"
__version_date__ = "2026-02-02"

import logging
from typing import List

from tree_sitter import Node

from .symbol_types import Symbol
from .language_builtins import TS_BUILTINS

logger = logging.getLogger(__name__)


class TypeScriptExtractor:
    """Extract TypeScript/JavaScript symbols from tree-sitter AST.

    This class handles all TypeScript/JavaScript-specific symbol extraction:
    - Functions
    - Classes
    - Interfaces
    - Type aliases
    - Reference extraction (imports, calls, inheritance, etc.)

    Attributes:
        None (stateless extractor)
    """

    def __init__(self):
        """Initialize TypeScript/JavaScript extractor."""
        logger.debug("TypeScriptExtractor initialized")

    def extract_typescript_references(self, node: Node) -> List[str]:
        """Extract all references from a TypeScript/JavaScript AST node.

        Extracts function calls, method calls, class inheritance, and type
        annotations from the given node and its children.

        Args:
            node: Tree-sitter Node to analyze (typically function/class body)

        Returns:
            List of unique reference names (excluding TS builtins)

        Covers (REQ-07):
            - Function calls: myFunc()
            - Method calls: obj.method()
            - Class extends: class Child extends Parent
            - Type annotations: param: MyType
        """
        references = set()

        def extract_from_node(n: Node) -> None:
            """Recursively extract references from node."""
            # Function calls: myFunc() or obj.method()
            if n.type == "call_expression":
                func_node = n.child_by_field_name("function")
                if func_node:
                    # Simple call: myFunc()
                    if func_node.type == "identifier":
                        name = func_node.text.decode()
                        if name not in TS_BUILTINS:
                            references.add(name)
                    # Method call: obj.method()
                    elif func_node.type == "member_expression":
                        prop_node = func_node.child_by_field_name("property")
                        if prop_node and prop_node.type == "property_identifier":
                            method_name = prop_node.text.decode()
                            if method_name not in TS_BUILTINS:
                                references.add(method_name)
                        # Also extract the object if it's an identifier
                        obj_node = func_node.child_by_field_name("object")
                        if obj_node and obj_node.type == "identifier":
                            obj_name = obj_node.text.decode()
                            if obj_name not in TS_BUILTINS:
                                references.add(obj_name)

            # Class inheritance: class Child extends Parent
            elif n.type == "class_declaration" or n.type == "class":
                # Look for class_heritage -> extends_clause
                for child in n.children:
                    if child.type == "class_heritage":
                        for heritage_child in child.children:
                            if heritage_child.type == "extends_clause":
                                # Get the extended class name
                                for ext_child in heritage_child.children:
                                    if ext_child.type == "identifier":
                                        base_name = ext_child.text.decode()
                                        if base_name not in TS_BUILTINS:
                                            references.add(base_name)
                                    elif ext_child.type == "member_expression":
                                        # Handle qualified names like module.ClassName
                                        prop = ext_child.child_by_field_name("property")
                                        if prop:
                                            references.add(prop.text.decode())

            # Type annotations: param: MyType, const x: MyType
            elif n.type == "type_annotation":
                for child in n.children:
                    if child.type == "type_identifier":
                        type_name = child.text.decode()
                        if type_name not in TS_BUILTINS:
                            references.add(type_name)
                    elif child.type == "generic_type":
                        # Handle Array<T>, Promise<T>, etc.
                        type_id = child.child_by_field_name("name")
                        if type_id and type_id.type == "type_identifier":
                            type_name = type_id.text.decode()
                            if type_name not in TS_BUILTINS:
                                references.add(type_name)
                        # Extract type arguments
                        type_args = child.child_by_field_name("type_arguments")
                        if type_args:
                            for arg in type_args.children:
                                if arg.type == "type_identifier":
                                    arg_name = arg.text.decode()
                                    if arg_name not in TS_BUILTINS:
                                        references.add(arg_name)

            # Also check for type_identifier anywhere (return types, etc.)
            elif n.type == "type_identifier":
                type_name = n.text.decode()
                if type_name not in TS_BUILTINS:
                    references.add(type_name)

            # Recurse to children
            for child in n.children:
                extract_from_node(child)

        extract_from_node(node)
        return sorted(references)

    def extract_ts_module_level_references(self, root_node: Node) -> List[str]:
        """Extract module-level references (imports) from TypeScript/JS AST.

        These are references that apply to the entire file, not specific symbols.

        Args:
            root_node: Root node of the parsed tree (program node)

        Returns:
            List of import references (imported names)
        """
        references = set()

        def extract_imports(n: Node) -> None:
            """Extract from import statements."""
            # import { X, Y } from 'module'
            # import X from 'module'
            # import * as X from 'module'
            if n.type == "import_statement":
                for child in n.children:
                    # Named imports: import { X, Y } from 'module'
                    if child.type == "import_clause":
                        for clause_child in child.children:
                            # Default import: import X from 'module'
                            if clause_child.type == "identifier":
                                name = clause_child.text.decode()
                                if name not in TS_BUILTINS:
                                    references.add(name)
                            # Named imports: { X, Y }
                            elif clause_child.type == "named_imports":
                                for spec in clause_child.children:
                                    if spec.type == "import_specifier":
                                        name_node = spec.child_by_field_name("name")
                                        if name_node:
                                            name = name_node.text.decode()
                                            if name not in TS_BUILTINS:
                                                references.add(name)
                                        # If no 'name' field, get from 'alias' or direct
                                        else:
                                            for spec_child in spec.children:
                                                if spec_child.type == "identifier":
                                                    name = spec_child.text.decode()
                                                    if name not in TS_BUILTINS:
                                                        references.add(name)
                                                    break
                            # Namespace import: import * as X from 'module'
                            elif clause_child.type == "namespace_import":
                                for ns_child in clause_child.children:
                                    if ns_child.type == "identifier":
                                        name = ns_child.text.decode()
                                        if name not in TS_BUILTINS:
                                            references.add(name)

            # Recurse for nested structures (e.g., inside export statements)
            for child in n.children:
                extract_imports(child)

        # Only process top-level statements
        for child in root_node.children:
            extract_imports(child)

        return sorted(references)

    def extract_typescript_symbols(self, tree, file_path: str) -> List[Symbol]:
        """Extract symbols from TypeScript/TSX AST using direct traversal.

        Args:
            tree: Parsed tree-sitter Tree
            file_path: Source file path

        Returns:
            List of Symbol objects
        """
        symbols = []

        # W2.5-B: Extract module-level references (imports) to add to all symbols
        module_refs = self.extract_ts_module_level_references(tree.root_node)

        def traverse(node: Node) -> None:
            """Recursively traverse AST and extract symbols."""
            # Function declarations
            if node.type == "function_declaration":
                name_node = node.child_by_field_name("name")
                params_node = node.child_by_field_name("parameters")

                if name_node:
                    name = name_node.text.decode()
                    params = params_node.text.decode() if params_node else "()"
                    signature = f"function {name}{params}"

                    # W2.5-B: Extract references from function body
                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbol = Symbol(
                        name=name,
                        type="function",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    )
                    symbols.append(symbol)

            # Class declarations (W2.5-B: added for TypeScript)
            elif node.type == "class_declaration":
                name_node = node.child_by_field_name("name")

                if name_node:
                    name = name_node.text.decode()

                    # Build signature with extends if present
                    signature = f"class {name}"
                    for child in node.children:
                        if child.type == "class_heritage":
                            heritage_text = child.text.decode()
                            signature = f"class {name} {heritage_text}"
                            break

                    # W2.5-B: Extract references from class body
                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbol = Symbol(
                        name=name,
                        type="class",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    )
                    symbols.append(symbol)

            # Interface declarations
            elif node.type == "interface_declaration":
                name_node = node.child_by_field_name("name")
                body_node = node.child_by_field_name("body")

                if name_node:
                    name = name_node.text.decode()
                    body = body_node.text.decode() if body_node else "{ }"

                    # Simplify body if too long
                    if len(body) > 100:
                        body = "{ ... }"

                    signature = f"interface {name} {body}"

                    # W2.5-B: Extract references from interface body
                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbol = Symbol(
                        name=name,
                        type="interface",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    )
                    symbols.append(symbol)

            # Type alias declarations
            elif node.type == "type_alias_declaration":
                name_node = node.child_by_field_name("name")

                if name_node:
                    name = name_node.text.decode()
                    signature = f"type {name} = ..."

                    # W2.5-B: Extract references from type definition
                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbol = Symbol(
                        name=name,
                        type="type",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    )
                    symbols.append(symbol)

            # Recurse to children
            for child in node.children:
                traverse(child)

        traverse(tree.root_node)
        logger.debug(f"Extracted {len(symbols)} TypeScript symbols from {file_path}")
        return symbols

    def extract_javascript_symbols(self, tree, file_path: str) -> List[Symbol]:
        """Extract symbols from JavaScript/JSX AST using direct traversal.

        Args:
            tree: Parsed tree-sitter Tree
            file_path: Source file path

        Returns:
            List of Symbol objects
        """
        symbols = []

        # W2.5-B: Extract module-level references (imports) - reuse TS method
        module_refs = self.extract_ts_module_level_references(tree.root_node)

        def traverse(node: Node) -> None:
            """Recursively traverse AST and extract symbols."""
            # Function declarations
            if node.type == "function_declaration":
                name_node = node.child_by_field_name("name")
                params_node = node.child_by_field_name("parameters")

                if name_node:
                    name = name_node.text.decode()
                    params = params_node.text.decode() if params_node else "()"
                    signature = f"function {name}{params}"

                    # W2.5-B: Extract references - reuse TS method
                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbol = Symbol(
                        name=name,
                        type="function",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    )
                    symbols.append(symbol)

            # Class declarations
            elif node.type == "class_declaration":
                name_node = node.child_by_field_name("name")

                if name_node:
                    name = name_node.text.decode()

                    # Build signature with extends if present
                    signature = f"class {name}"
                    for child in node.children:
                        if child.type == "class_heritage":
                            heritage_text = child.text.decode()
                            signature = f"class {name} {heritage_text}"
                            break

                    # W2.5-B: Extract references - reuse TS method
                    body_refs = self.extract_typescript_references(node)
                    all_refs = sorted(set(body_refs) | set(module_refs))

                    symbol = Symbol(
                        name=name,
                        type="class",
                        file=file_path,
                        line=name_node.start_point[0] + 1,
                        signature=signature,
                        references=all_refs,
                    )
                    symbols.append(symbol)

            # Recurse to children
            for child in node.children:
                traverse(child)

        traverse(tree.root_node)
        logger.debug(f"Extracted {len(symbols)} JavaScript symbols from {file_path}")
        return symbols
