#!/bin/bash
#
# compliance-check.sh - Verifica che agenti seguano le regole
#
# Cosa controlla:
#   1. Report recenti contengono COSTITUZIONE-APPLIED
#   2. Output contengono PRE-FLIGHT-CHECK o POST-FLIGHT
#   3. File salvati in .sncp/ (non solo in memoria)
#
# Uso:
#   compliance-check.sh [progetto]
#   compliance-check.sh --all
#   compliance-check.sh --report
#
# Versione: 1.0.0
# Data: 2026-01-15
# Sessione 217 - GAP #3 Implementation
#
# "Le regole esistono per essere SEGUITE!" - Cervella & Rafa
#

set -e

# Colori
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Path base
SNCP_BASE="$HOME/Developer/CervellaSwarm/.sncp"
PROGETTI_DIR="$SNCP_BASE/progetti"
LOG_DIR="$SNCP_BASE/logs"

# Contatori globali
TOTAL_FILES=0
COMPLIANT=0
VIOLATIONS=0

# Funzione: Mostra help
show_help() {
    echo "compliance-check.sh - Verifica compliance agenti"
    echo ""
    echo "Uso:"
    echo "  compliance-check.sh [progetto]    Check singolo progetto"
    echo "  compliance-check.sh --all         Check tutti i progetti"
    echo "  compliance-check.sh --report      Genera report completo"
    echo "  compliance-check.sh --help        Mostra questo help"
    echo ""
    echo "Cosa controlla:"
    echo "  - COSTITUZIONE-APPLIED nei report"
    echo "  - PRE-FLIGHT-CHECK/POST-FLIGHT markers"
    echo "  - Output salvati in SNCP"
}

# Funzione: Check singolo file
check_file() {
    local FILE="$1"
    local FILENAME=$(basename "$FILE")
    local ISSUES=""

    ((TOTAL_FILES++))

    # Skip file troppo piccoli
    if [ ! -s "$FILE" ]; then
        return 0
    fi

    # Check COSTITUZIONE-APPLIED (solo per report)
    if [[ "$FILENAME" == *"REPORT"* ]] || [[ "$FILENAME" == *"AUDIT"* ]] || [[ "$FILENAME" == *"REVIEW"* ]]; then
        if ! grep -q "COSTITUZIONE-APPLIED" "$FILE" 2>/dev/null; then
            ISSUES="${ISSUES}manca COSTITUZIONE-APPLIED; "
        fi
    fi

    # Check PRE-FLIGHT o POST-FLIGHT (solo per report recenti)
    if [[ "$FILENAME" == *"202601"* ]]; then
        if ! grep -qE "(PRE-FLIGHT|POST-FLIGHT|Principio usato)" "$FILE" 2>/dev/null; then
            # Solo warning, non errore critico
            ISSUES="${ISSUES}nessun marker flight; "
        fi
    fi

    # Risultato
    if [ -z "$ISSUES" ]; then
        ((COMPLIANT++))
        return 0
    else
        ((VIOLATIONS++))
        echo -e "  ${YELLOW}!${NC} $FILENAME: $ISSUES"
        return 1
    fi
}

# Funzione: Check progetto
check_project() {
    local PROJECT="$1"
    local PROJECT_DIR="$PROGETTI_DIR/$PROJECT"

    if [ ! -d "$PROJECT_DIR" ]; then
        echo -e "${RED}Progetto '$PROJECT' non trovato${NC}"
        return 1
    fi

    echo -e "${BLUE}Progetto: $PROJECT${NC}"
    echo ""

    # Check reports
    if [ -d "$PROJECT_DIR/reports" ]; then
        echo -e "  ${CYAN}Reports:${NC}"
        for f in "$PROJECT_DIR"/reports/*.md; do
            [ -f "$f" ] && check_file "$f"
        done
    fi

    # Check ricerche
    if [ -d "$PROJECT_DIR/ricerche" ]; then
        echo -e "  ${CYAN}Ricerche:${NC}"
        for f in "$PROJECT_DIR"/ricerche/*.md; do
            [ -f "$f" ] && check_file "$f"
        done
    fi

    echo ""
}

# Funzione: Genera report
generate_report() {
    mkdir -p "$LOG_DIR"
    local REPORT_FILE="$LOG_DIR/compliance_$(date +%Y%m%d).md"

    echo "# Compliance Report - $(date +%Y-%m-%d)" > "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "## Summary" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "- **Files checked:** $TOTAL_FILES" >> "$REPORT_FILE"
    echo "- **Compliant:** $COMPLIANT" >> "$REPORT_FILE"
    echo "- **Violations:** $VIOLATIONS" >> "$REPORT_FILE"

    if [ "$TOTAL_FILES" -gt 0 ]; then
        local RATE=$((COMPLIANT * 100 / TOTAL_FILES))
        echo "- **Compliance rate:** ${RATE}%" >> "$REPORT_FILE"
    fi

    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "*Generated by compliance-check.sh*" >> "$REPORT_FILE"

    echo -e "${GREEN}Report salvato:${NC} $REPORT_FILE"
}

# Funzione: Mostra summary
show_summary() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════${NC}"
    echo -e "${BLUE}           COMPLIANCE SUMMARY          ${NC}"
    echo -e "${BLUE}═══════════════════════════════════════${NC}"
    echo ""
    echo -e "  Files checked:  ${CYAN}$TOTAL_FILES${NC}"
    echo -e "  Compliant:      ${GREEN}$COMPLIANT${NC}"
    echo -e "  Violations:     ${YELLOW}$VIOLATIONS${NC}"

    if [ "$TOTAL_FILES" -gt 0 ]; then
        local RATE=$((COMPLIANT * 100 / TOTAL_FILES))
        if [ "$RATE" -ge 80 ]; then
            echo -e "  Compliance:     ${GREEN}${RATE}%${NC}"
        elif [ "$RATE" -ge 60 ]; then
            echo -e "  Compliance:     ${YELLOW}${RATE}%${NC}"
        else
            echo -e "  Compliance:     ${RED}${RATE}%${NC}"
        fi
    fi

    echo ""

    if [ "$VIOLATIONS" -eq 0 ]; then
        echo -e "${GREEN}Tutto OK! Regole seguite!${NC}"
    else
        echo -e "${YELLOW}Attenzione: $VIOLATIONS file con issues${NC}"
        echo -e "Aggiungi COSTITUZIONE-APPLIED ai report!"
    fi

    echo ""
}

# Main
case "${1:-}" in
    --help|-h)
        show_help
        exit 0
        ;;
    --all)
        echo -e "${BLUE}Compliance Check - Tutti i progetti${NC}"
        echo ""
        for p in cervellaswarm miracollo contabilita; do
            check_project "$p" 2>/dev/null || true
        done
        show_summary
        ;;
    --report)
        echo -e "${BLUE}Generazione Report Compliance${NC}"
        echo ""
        for p in cervellaswarm miracollo contabilita; do
            check_project "$p" 2>/dev/null || true
        done
        show_summary
        generate_report
        ;;
    "")
        # Default: progetto corrente
        CWD=$(pwd)
        if [[ "$CWD" == *"miracollo"* ]]; then
            check_project "miracollo"
        elif [[ "$CWD" == *"Contabilita"* ]]; then
            check_project "contabilita"
        else
            check_project "cervellaswarm"
        fi
        show_summary
        ;;
    *)
        check_project "$1"
        show_summary
        ;;
esac

exit 0
