# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CervellaSwarm Contributors

"""
Session Checkpoint - SessionEnd/PreCompact Hook for Claude Code.

Automatically saves project state at session end or before context compaction.
Creates/updates a state file with git status, recent commits, and a summary section.

Usage in Claude Code settings.json:
    "SessionEnd": [{
        "matcher": "",
        "hooks": [{"type": "command", "command": "cervella-session-checkpoint"}]
    }]

    "PreCompact": [{
        "matcher": "",
        "hooks": [{"type": "command", "command": "cervella-session-checkpoint"}]
    }]
"""

import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .config import get_hook_config

__version__ = "1.0.0"


def find_project_root(cwd: str) -> Path | None:
    """Find project root by walking up to the nearest .git directory."""
    current = Path(cwd)
    for parent in [current, *current.parents]:
        if (parent / ".git").exists():
            return parent
    return None


def git_command(args: list[str], cwd: str) -> str:
    """Run a git command and return output."""
    try:
        result = subprocess.run(
            ["git"] + args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception:
        return ""


def get_git_status(cwd: str) -> str:
    """Get a summary of git status."""
    status = git_command(["status", "--porcelain"], cwd)
    if not status:
        return "Clean working tree"

    lines = status.split("\n")
    modified = sum(1 for l in lines if l.startswith(" M") or l.startswith("M "))
    added = sum(1 for l in lines if l.startswith("A ") or l.startswith("??"))
    deleted = sum(1 for l in lines if l.startswith(" D") or l.startswith("D "))

    parts = []
    if modified:
        parts.append(f"{modified} modified")
    if added:
        parts.append(f"{added} new/untracked")
    if deleted:
        parts.append(f"{deleted} deleted")

    return ", ".join(parts) if parts else f"{len(lines)} changes"


def get_recent_commits(cwd: str, count: int = 5) -> str:
    """Get recent commit messages."""
    log = git_command(
        ["log", f"--oneline", f"-{count}", "--no-decorate"], cwd
    )
    return log if log else "No commits found"


def get_branch(cwd: str) -> str:
    """Get current branch name."""
    return git_command(["branch", "--show-current"], cwd) or "unknown"


def build_checkpoint(cwd: str, config: dict) -> str:
    """Build the checkpoint content."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    branch = get_branch(cwd)
    project_name = Path(cwd).name

    lines = [
        f"# Session State - {project_name}",
        "",
        f"> Last updated: {now}",
        f"> Branch: {branch}",
        "",
        "---",
        "",
    ]

    if config.get("include_git_status", True):
        status = get_git_status(cwd)
        lines.extend([
            "## Git Status",
            f"- {status}",
            "",
        ])

    if config.get("include_recent_commits", True):
        commits = get_recent_commits(cwd)
        lines.extend([
            "## Recent Commits",
            "```",
            commits,
            "```",
            "",
        ])

    lines.extend([
        "## Current Focus",
        "",
        "<!-- This section is auto-generated as a placeholder. -->",
        "<!-- Edit manually to describe what you're working on. -->",
        "",
        "---",
        "",
        "*Auto-generated by cervella-session-checkpoint*",
    ])

    return "\n".join(lines)


def main():
    """Entry point."""
    try:
        input_data = json.load(sys.stdin)
    except Exception:
        input_data = {}

    cwd = input_data.get("cwd", os.getcwd())
    project_root = find_project_root(cwd)

    if not project_root:
        print(json.dumps({"result": "Not a git repository, skipping checkpoint"}))
        return 0

    config = get_hook_config("session_checkpoint")
    state_file = config.get("state_file", "SESSION_STATE.md")
    max_lines = config.get("max_lines", 200)

    state_path = project_root / state_file
    checkpoint = build_checkpoint(str(project_root), config)

    # Respect max_lines
    checkpoint_lines = checkpoint.split("\n")
    if len(checkpoint_lines) > max_lines:
        checkpoint = "\n".join(checkpoint_lines[:max_lines])

    try:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.write_text(checkpoint + "\n", encoding="utf-8")
    except Exception:
        pass

    print(json.dumps({"result": f"Checkpoint saved to {state_file}"}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
