# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CervellaSwarm Contributors

"""Shared fixtures for cervellaswarm-session-memory tests."""

import pytest


@pytest.fixture
def tmp_memory_dir(tmp_path):
    """Create a .session-memory directory with subdirectories."""
    memory_dir = tmp_path / ".session-memory"
    memory_dir.mkdir()
    (memory_dir / "test-project").mkdir()
    (memory_dir / "test-project" / "archive").mkdir()
    return memory_dir


@pytest.fixture
def tmp_project_root(tmp_path):
    """Create a project root directory with a .git marker."""
    project_root = tmp_path / "my-project"
    project_root.mkdir()
    (project_root / ".git").mkdir()
    return project_root


@pytest.fixture
def sample_config():
    """Return a valid config dict for project 'test-project'."""
    return {
        "memory_dir": ".session-memory",
        "state_file": "SESSION_STATE.md",
        "compass_file": "PROJECT_COMPASS.md",
        "max_lines": 300,
        "warning_lines": 200,
        "quality": {
            "weights": {
                "actionability": 0.30,
                "specificity": 0.30,
                "freshness": 0.20,
                "conciseness": 0.20,
            },
            "target_score": 8.0,
        },
        "secrets": {
            "extra_patterns": [],
            "skip_files": [],
        },
        "projects": {"test-project": {}},
    }


@pytest.fixture
def sample_state_content():
    """Return valid Markdown content for a session state file."""
    return (
        "# Session State - Test Project\n"
        "\n"
        "> **Last updated:** 2026-02-19 - Session 1\n"
        "> **Status:** In progress\n"
        "\n"
        "---\n"
        "\n"
        "## SESSION 1 - Initial Setup\n"
        "\n"
        "### Completed\n"
        "\n"
        "| Task | Status | Notes |\n"
        "|------|--------|-------|\n"
        "| Initialize project | DONE | v1.0.0 on 2026-02-19 |\n"
        "\n"
        "## NEXT STEPS\n"
        "\n"
        "1. [ ] **Define scope** - Outline goals\n"
        "2. [ ] **Set up environment** - Install deps\n"
        "3. [ ] **Create implementation** - Start building\n"
        "\n"
        "---\n"
        "\n"
        "*Generated by cervellaswarm-session-memory v0.1.0*\n"
    )


@pytest.fixture
def sample_state_file(tmp_path, sample_state_content):
    """Write sample state content to a file and return the Path."""
    state_file = tmp_path / "SESSION_STATE_test-project.md"
    state_file.write_text(sample_state_content, encoding="utf-8")
    return state_file


@pytest.fixture
def config_file(tmp_path):
    """Write a session-memory.yaml config file and return its path."""
    content = (
        "memory_dir: .session-memory\n"
        "max_lines: 300\n"
        "warning_lines: 200\n"
        "quality:\n"
        "  target_score: 8.0\n"
    )
    cfg = tmp_path / "session-memory.yaml"
    cfg.write_text(content, encoding="utf-8")
    return cfg
